services:
  - type: web
    name: pdf-extractor-api # Or whatever name you chose
    env: python
    region: oregon # Or your chosen region
    plan: free
    systemPackages:
      - build-essential
      - libjpeg-dev
      - zlib1g-dev
      - libfreetype6-dev
      - liblcms2-dev
      - libopenjp2-7-dev
      - libwebp-dev
      - tesseract-ocr
      - pkg-config
      - libtesseract-dev # <--- Add this crucial line
    buildCommand: ""
    startCommand: "gunicorn main:app"
    envVars:
      - key: OPENROUTER_API_KEY
        value: "REPLACE_THIS_WITH_YOUR_KEY_IN_RENDER_DASHBOARD"
